### PR TITLE
Upgrade to Spring Cloud 2020.0.2 Ilford

### LINKED ISSUE #109: Spring Boot 2.4.x compatibility (update to Spring Cloud Illford)
It looks like the new version of [Spring Cloud (Illford) ](https://spring.io/blog/2020/12/22/spring-cloud-2020-0-0-aka-ilford-is-available) is now generally available which is compatible with Spring Boot 2.4.x.

Opening this issue so that folks can track when support for 2.4.x is added.

Thank you for all of your work on this project.

### PR DESCRIPTION
**Pull request by daniel-dios**
Hi friends from Zalando, this is @rogervinas and @daniel-dios from @AdevintaSpain
Thank you for this amazing library, we are using it a lot! 🤓❤️

This PR fixes #109

Actually, we fixed it live on Twitch: https://www.twitch.tv/videos/1013178964

Cheers!

### CODE REVIEW

**Comment by paugay** [comment]
bravo @daniel-dios and @rogervinas 👏 ❤️

**Comment by jesjos** [comment]
We've successfully tested this locally in one of our projects! Hope it can be merged eventually. 👍

**Comment by evankellogg** [comment]
@roskenet @oussewa any chance to get some eyes on this for approvals?

**Comment by mrandi** [comment]
@oussewa could you please check this?

**Comment by oussewa** [comment]
👍

**Comment by roskenet** [comment]
:+1:

**Pull request merged**
