### PR TITLE
make this repository compliant to Zalando OSS guidelines

### LINKED ISSUE #19: Add Contributing.md
This will A) help the project become contributor-friendly; B) bring it closer into compliance with our OSS RoP.

Without the file we'll have to archive in GHE.

### LINKED ISSUE #22: Add Security.md
In order to comply with Zalando's OSS guidelines. Furthermore this gives users possibility to report security threats.

### PR DESCRIPTION
**Pull request by harti2006**
* add CONTRIBUTING.md - fixes #19
* add SECURITY.md - fixes #22

### CODE REVIEW

**Comment by maschleg** [comment]
looks good. What about these Rules?:

"3. Use the MIT license only"
"5. Include a MAINTAINERS file. Every project MUST have at least two named maintainers." -> You can add me as maintainer :)

**Comment by harti2006** [comment]
@maschleg thanks, will add you as maintainer. Regarding the license: I'm not sure if it is allowed to just change it for existing projects. Are there any legal restrictions?

**Comment by maschleg** [comment]
good question we should do it in separate issue and ask legal before. I will create a issue.

**Comment by harti2006** [comment]
I just rebased this branch onto the latest changes for release 1.7, which should fix the Travis build issues.

**Comment by maschleg** [comment]
👍

**Comment by harti2006** [comment]
:+1:

**Pull request merged**
